# Generated by Django 3.0.8 on 2020-07-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200723_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('G', 'Gadgets'), ('F', 'Food'), ('C', 'Clothes'), ('S', 'Shoes')], max_length=2, null=True)),
                ('product_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductPhoto')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.Profile')),
            ],
        ),
    ]
